/// Generated by AssetsRefGenerator on 2023/08/03
class AppAssets {
  static const String about_us = "assets/images/about_us.png";
  static const String aboutUs = "assets/svgs/aboutUs.svg";
  static const String arrowRight = "assets/svgs/arrowRight.svg";

  static const String bell = "assets/images/bell.png";
  static const String blank_profile = "assets/images/blank_profile.png";
  static const String blog = "assets/images/blog.png";
  static const String book = "assets/svgs/book.svg";
  static const String booknotfound = "assets/images/booknotfound.png";
  static const String books = "assets/images/books.png";
  static const String calendar = "assets/svgs/calendar.svg";
  static const String calendar2 = "assets/svgs/calendar2.svg";
  static const String certificate = "assets/images/certificate.png";
  static const String changePassword = "assets/svgs/changePassword.svg";
  static const String check = "assets/svgs/check.svg";
  static const String circleImage = "assets/images/circleImage.png";
  static const String clock = "assets/svgs/clock.svg";
  static const String copy = "assets/svgs/copy.svg";
  static const String download = "assets/svgs/download.svg";
  static const String edit_profile = "assets/svgs/edit_profile.svg";
  static const String editProfile = "assets/svgs/editProfile.svg";
  static const String examResult = "assets/svgs/examResult.svg";
  static const String eye_slash = "assets/svgs/eye_slash.svg";
  static const String eyeSlash = "assets/svgs/eyeSlash.svg";
  static const String facebook = "assets/images/facebook.png";
  static const String fast_forward = "assets/images/fast-forward.png";
  static const String fast_ = "assets/images/fast-forward.png";
  static const String forgot_password = "assets/images/forgot_password.png";
  static const String forgotPassword = "assets/svgs/forgotPassword.svg";
  static const String gallery_edit = "assets/svgs/gallery_edit.svg";
  static const String google = "assets/images/google.png";
  static const String heart = "assets/images/heart.png";
  static const String holiday = "assets/svgs/holiday.svg";
  static const String home = "assets/svgs/home.svg";
  static const String ic_radio_selected = "assets/images/ic_radio_selected.png"; 
   static const String ic_physical_Training= "assets/images/ic_physical_Training.png"; 
   static const String ic_live_Training= "assets/images/ic_live.training.png"; 
     static const String ic_recorded_Training= "assets/images/ic_recorded.training.png"; 
   
   
  
  static const String ic_redio_unselected =
      "assets/images/ic_redio_unselected.png";
  static const String ic_splash = "assets/images/ic_splash_black.png";
  static const String icon = "assets/images/icon.png";
  static const String icon1 = "assets/images/icon1.png";
  static const String idCard = "assets/svgs/idCard.svg";
  static const String img = "assets/images/img.png";
  static const String introImage = "assets/images/introImage.png";
  static const String katon_app_icon = "assets/images/katon_app_icon.png";

  static const String lock = "assets/svgs/lock.svg";
  static const String login = "assets/images/login.png";
  static const String logo = "assets/svgs/logo.svg";
  static const String logout = "assets/images/logout.png";

  static const String mail = "assets/svgs/mail.svg";
  static const String news = "assets/images/news.png";
  static const String no_data = "assets/images/no_data.svg";
  static const String no_internet = "assets/images/no_internet.png";
  static const String notes = "assets/images/notes.png";
  static const String notification = "assets/svgs/notification.svg";
  static const String order_history = "assets/svgs/order_history.svg";
  static const String pdf = "assets/svgs/pdf.svg";
  static const String placeholder = "assets/images/placeholder.jpg";
  static const String remedial = "assets/svgs/remedial.svg";
  static const String round1 = "assets/svgs/round1.svg";
  static const String round2 = "assets/svgs/round2.svg";
  static const String settings = "assets/svgs/settings.svg";
  static const String signform_logo = "assets/images/signform_logo.jpg";
  static const String slider_1 = "assets/images/slider_1.png";
  static const String slider_2 = "assets/images/slider_2.png";
  static const String slider_3 = "assets/images/slider_3.png";
  static const String sms = "assets/svgs/sms.svg";
  static const String social_media = "assets/images/social-media.png";
  static const String splash = "assets/images/splash.png";
  static const String star = "assets/svgs/star.svg";
  static const String t4_walk_bg = "assets/images/t4_walk_bg.png";
  static const String teacher = "assets/svgs/teacher.svg";
  static const String timer = "assets/svgs/timer.svg";
  static const String unlock = "assets/images/unlock.png";
  static const String upcoming_event = "assets/svgs/upcoming_event.svg";
  static const String user = "assets/images/user.png";
  static const String user_group = "assets/svgs/user_group.svg";
  static const String walk_through = "assets/images/walk_through.png";
  static const String walkthrough2 = "assets/images/walkthrough2.jpg";
  static const String white_icon = "assets/svgs/white_icon.svg";

 static const String ic_loder_black = "assets/images/ic_loder_black.png";
  static const String ic_splash_black = "assets/images/ic_splash_black.png";
  static const String ic_user = "assets/svgs/ic_user.svg";
  static const String ic_visibility = "assets/svgs/visibility.svg";
  static const String ic_visibility_off = "assets/svgs/visibility_off.svg";
  static const String ic_library = "assets/images/library.png";
  static const String ic_practice = "assets/images/practice.png";
  static const String ic_connect = "assets/images/connect.png";
  static const String ic_tution = "assets/images/tution.png";
  static const String ic_profile = "assets/images/profile.png";
  static const String ic_settings = "assets/images/settings.png";
  static const String ic_logout = "assets/images/logout.png";

  //!Library
  static const String ic_subject1 = "assets/images/library/english.png";
  static const String ic_subject2 = "assets/images/library/mathematics.png";
  static const String ic_subject3 = "assets/images/library/science.png";
  static const String ic_subject4 = "assets/images/library/social_studies.png";
  static const String ic_subject5 = "assets/images/library/computer.png";
  static const String ic_subject6 = "assets/images/library/creative_art.png";
  static const String e_book = "assets/images/library/e_book.png";
   static const String labrary_videos = "assets/images/library/labrary_videos.png";
   
  static const String ic_arrow_down = "assets/images/arrow_down.png";
  static const String ic_arrow_left = "assets/images/arrow_left.png";
  static const String ic_book = "assets/images/book.png";
  static const String ic_share = "assets/images/share.png";
  static const String ic_download = "assets/images/download.png";
  static const String ic_download_finish = "assets/images/finish_download.png";
  static const String ic_document = "assets/images/document.png";
  static const String ic_pdf = "assets/images/pdf.png";
  static const String ic_epub = "assets/images/epub.png";
  static const String ic_play_outline = "assets/images/play_outline.png";
  static const String ic_play = "assets/images/play.png";
  static const String ic_smile_emoji = "assets/images/smile_emoji.png";
  static const String ic_gallary = "assets/images/gallary.png";
  static const String ic_like_outline = "assets/images/like_outline.png";
  static const String ic_message = "assets/images/message.png";
  static const String ic_share_connect = "assets/images/share_connect.png";
  static const String ic_add_image = "assets/images/add_image.png";
  static const String ic_email = "assets/images/email.png";
  static const String ic_notification = "assets/images/notification.png";
  static const String ic_help = "assets/images/help.png";
  static const String ic_lock = "assets/images/lock.png";
  static const String ic_lock_fill = "assets/images/lock_fill.png";
  static const String ic_delete_account = "assets/images/delete_account.png";
  static const String ic_send = "assets/images/send.png";
  static const String ic_mail = "assets/images/mail.png";
  static const String ic_assignment = "assets/images/assignment.png";
  

  static const String ic_pastQuestion = "assets/images/past-questions.png";
  static const String ic_selfAssessment = "assets/images/self-assessment.png";

  //!teacher
  static const String ic_training = "assets/images/training.png";

  ///
  static const String Autography = "assets/fonts/signfonts/Autography.otf";
  static const String Betterlett = "assets/fonts/signfonts/Betterlett.otf";
  static const String Darlington = "assets/fonts/signfonts/Darlington.ttf";
  static const String Flighty = "assets/fonts/signfonts/Flighty.ttf";
  static const String HealingFairyBoldItalic =
      "assets/fonts/signfonts/HealingFairyBoldItalic.otf";
  static const String KimberlySignature =
      "assets/fonts/signfonts/KimberlySignature.otf";
  static const String Pontgraph = "assets/fonts/signfonts/Pontgraph.otf";
  static const String Poppins_Black = "assets/fonts/Poppins-Black.otf";
  static const String Poppins_BlackItalic =
      "assets/fonts/Poppins-BlackItalic.otf";
  static const String Poppins_Bold = "assets/fonts/Poppins-Bold.otf";
  static const String Poppins_BoldItalic =
      "assets/fonts/Poppins-BoldItalic.otf";
  static const String Poppins_ExtraBold = "assets/fonts/Poppins-ExtraBold.otf";
  static const String Poppins_ExtraBoldItalic =
      "assets/fonts/Poppins-ExtraBoldItalic.otf";
  static const String Poppins_ExtraLight =
      "assets/fonts/Poppins-ExtraLight.otf";
  static const String Poppins_ExtraLightItalic =
      "assets/fonts/Poppins-ExtraLightItalic.otf";
  static const String Poppins_Italic = "assets/fonts/Poppins-Italic.otf";
  static const String Poppins_Light = "assets/fonts/Poppins-Light.otf";
  static const String Poppins_LightItalic =
      "assets/fonts/Poppins-LightItalic.otf";
  static const String Poppins_Medium = "assets/fonts/Poppins-Medium.otf";
  static const String Poppins_MediumItalic =
      "assets/fonts/Poppins-MediumItalic.otf";
  static const String Poppins_Regular = "assets/fonts/Poppins-Regular.otf";
  static const String Poppins_SemiBold = "assets/fonts/Poppins-SemiBold.otf";
  static const String Poppins_SemiBoldItalic =
      "assets/fonts/Poppins-SemiBoldItalic.otf";
  static const String Poppins_Thin = "assets/fonts/Poppins-Thin.otf";
  static const String Poppins_ThinItalic =
      "assets/fonts/Poppins-ThinItalic.otf";
  static const String Reinatha = "assets/fonts/signfonts/Reinatha.ttf";
}
